### ISSUE TITLE
Transparente Gif not working as expected

### ISSUE THREAD

**Issue by tinchoforever** [mayognaise/aframe-gif-shader#2]
Hello everyone!
I have tried the component using transparent gif and it seems that the material doesn't clean every frame and keeps all the frames while the animation continues.
Any Idea why is this?
Are there any work arounds or plans to fix it or where we can check to fix it?

Thanks!

![](https://cloud.githubusercontent.com/assets/719504/20226268/3ef2368c-a826-11e6-867b-74f59032c889.gif)
his is the GIF
http://belisario.herokuapp.com/belisariocorre_v01.gif

**Comment by tinchoforever** [comment]
`<head>
    <title>Belisario, el pequeño gran héroe del cosmos - serie animada fulldome -</title>
 

    

   <meta name="twitter:site" content="@belisario_fulld">  
   <meta name="twitter:title" content="Belisario, el pequeño gran héroe del cosmos">
   <meta name="twitter:description" content="Belisario, el pequeño gran héroe del cosmos. Una serie animada fulldome producida por el Planetario Ciudad de La Plata junto a Celeste Estudio Creativo y Cut to the Chase.">
    <meta name="twitter:image" content="https://belisario.herokuapp.com/no-vr/imgs/belisarioescape.jpg">
    <meta name="twitter:player" content="https://belisario.herokuapp.com/index.html">
    <meta name="twitter:player:width" content="600">
    <meta name="twitter:player:height" content="370">
    

    <meta property="og:title" content="Belisario, el pequeño gran héroe del cosmos">
    <meta property="og:url" content="https://belisario.herokuapp.com/">
    <meta property="og:description"  content="Belisario, el pequeño gran héroe del cosmos. Una serie animada fulldome producida por el Planetario Ciudad de La Plata junto a Celeste Estudio Creativo y Cut to the Chase.">
    <meta property="og:type" content="video.movie" /> 
    <meta property="og:image" content="https://belisario.herokuapp.com//no-vr/imgs/belisarioescape.jpg" />
     





  <script src="https://aframe.io/releases/0.2.0/aframe.min.js"></script>
  <script src="https://rawgit.com/mayognaise/aframe-gif-shader/master/dist/aframe-gif-shader.min.js"></script>
  <script src="//cdn.rawgit.com/donmccurdy/aframe-extras/v1.17.0/dist/aframe-extras.min.js"></script>
</head>
  <link rel="stylesheet" href="styles/main.css">
   <script>
    var gyroPresent = false;
    window.addEventListener("devicemotion", function(event){
        if(event.rotationRate.alpha || event.rotationRate.beta || event.rotationRate.gamma)
            gyroPresent = true;
    });

   if (navigator.getVRDevices) {
      console.log('vr')
    } else if (navigator.mozGetVRDevices) {
      console.log('vr')
    } else {      
      window.location =  window.location + '/no-vr'
      console.log('no-vr')
    }
   </script>
   
<body>
  <a-scene>
    <img  id="cardboard" src="img/cardboard.png">
      
        <img id="titulo01" src="titulos.png">
        <img id="sphere360-01" src="images/360-01.jpg">
        <img id="sphere360-02" src="images/360-02.jpg">


        <img id="textura00" src="images/escena-01.png">
        <img id="textura01" src="images/escena-02.png">
        <img id="textura02" src="images/escena-03.png">
        <img id="textura03" src="images/escena-04.png">
        <img id="textura04" src="images/escena-05.png">
        <img id="textura05" src="images/escena-06.png">
        <img id="textura06" src="images/escena-07.png">
        <img id="textura07" src="images/escena-08.png">
        <img id="textura08" src="images/escena-09.png">
        <img id="textura09" src="images/escena-10.png">
      


      </a-assets>
    <a-image src="#titulo01" opacity="0"  look-at="#miradas-cam" position="0 2 -260" width="300" height="300">
        <a-animation attribute="opacity" from="0" to="1" begin="0" dur="5000"> </a-animation>
        <a-animation attribute="opacity" from="1" to="0" begin="5000" dur="5000"> </a-animation>
        <a-animation attribute="visible" begin="10000" to="false"></a-animation>
       </a-image>
    <a-entity  position="0 0 0" 
        rotation="90 0 0" geometry="primitive: circle; radius: 4"
          material="color: transparent">
          
           <a-animation attribute="rotation"
               dur="10000"
               easing="linear"
               to="90 0 360"
               repeat="indefinite"></a-animation>
               
           <a-entity rotation="270 -180 180" 
           position="0 3 -0.5" 
           geometry="primitive:plane;" 
           material="shader:gif;side:double;src:url(otro.otro.gif);transparent:true;opacity:1;">
            </a-entity>
      </a-entity>
    
    
      
      <a-sky  src="#sphere360-01" opacity="0" visibility="false" rotation="0 -75 0">
              <a-animation attribute="visible" begin="8000" to="true" id="firstPlay"></a-animation>
              <a-animation attribute="opacity" from="0" to="1"
               begin="8000" dur="5000">
              </a-animation>
               <a-animation attribute="opacity" from="1" to="0"
               begin="40000" dur="5000">
             </a-animation>
             <a-animation attribute="visible" begin="45000" to="false"></a-animation>

    </a-sky>
     <a-sky  src="#sphere360-02" opacity="0" visibility="false" rotation="0 -75 0">
              <a-animation attribute="visible" begin="40000" to="true" id="firstPlay"></a-animation>
              <a-animation attribute="opacity" from="0" to="1"
               begin="40000" dur="5000">
              </a-animation>
               <a-animation attribute="opacity" from="1" to="0"
               begin="80000" dur="5000">
             </a-animation>
             <a-animation attribute="visible" begin="85000" to="false"></a-animation>

    </a-sky>

    


        <a-plane id="plano00" class="foto" src="#textura00" color="#FFF" height="1" width="1" position="0 1.6 -1"  look-at="[camera]"></a-plane>
        <a-plane id="plano01" class="foto" src="#textura01" color="#FFF" height="1" width="1" position="0 1.6 -1"  look-at="[camera]"></a-plane>
        <a-plane id="plano02" class="foto" src="#textura02" color="#FFF" height="1" width="1" position="0 1.6 -1"  look-at="[camera]"></a-plane>
        <a-plane id="plano03" class="foto" src="#textura03" color="#FFF" height="1" width="1" position="0 1.6 -1"  look-at="[camera]"></a-plane>
        <a-plane id="plano04" class="foto" src="#textura04" color="#FFF" height="1" width="1" position="0 1.6 -1"  look-at="[camera]"></a-plane>
        <a-plane id="plano05" class="foto" src="#textura05" color="#FFF" height="1" width="1" position="0 1.6 -1"  look-at="[camera]"></a-plane>
        <a-plane id="plano06" class="foto" src="#textura06" color="#FFF" height="1" width="1" position="0 1.6 -1"  look-at="[camera]"></a-plane>
        <a-plane id="plano07" class="foto" src="#textura07" color="#FFF" height="1" width="1" position="0 1.6 -1"  look-at="[camera]"></a-plane>
        <a-plane id="plano08" class="foto" src="#textura08" color="#FFF" height="1" width="1" position="0 1.6 -1"  look-at="[camera]"></a-plane>
        <a-plane id="plano09" class="foto" src="#textura09" color="#FFF" height="1" width="1" position="0 1.6 -1"  look-at="[camera]"></a-plane>
    <a-camera id="miradas-cam" camera universal-controls mouse-controls position="0 1 0">
     
      <a-entity id="soundtrack" geometry="primitive: plane" material="color: transparent" look-at="#miradas-cam" sound="src:soundtrack.mp3; loop:true;autoplay:true;volume:0.5;"  position="0 0 1"></a-entity>
    
  </a-scene>
   <script src="scripts/app.js"></script>
     <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'xxxxx', 'auto');
  ga('send', 'pageview');

</script>
</body>`

**Comment by mayognaise** [comment]
Hi @tinchoforever, sorry for late replying. I could reproduce the issue.
I will debug it when I have time, though it's been hectic these days... :/

**Comment by aliy321** [comment]
is there another work around for this?

**Comment by mayognaise** [comment]
@tinchoforever @aliy321 hi! im so sorry for the late response.
so i debugged and i could reproduce the issue.
i assume it's how gif has made. it picks color different between previous and current frames and somehow this causes the error.
i will debug more if i can make it work, but no guarantee if it is possible.
thank you so much for your patient.

**Comment by keangame** [comment]
I just change aframe-gif-component.js as:

__draw: function __draw() {
	    
	      if (this.clearimg) {
            this.__ctx.clearRect( 0, 0, this.__width, this.__height);
        }else{
	          this.__ctx.drawImage(this.__frames[this.__frameIdx], 0, 0, this.__width, this.__height);
	          this.__texture.needsUpdate = true;
        }
	      if (this.clearimg)
	          this.clearimg = false;
         else
	          this.clearimg = true;
	
	  },
this may fix your problem.

**Comment by keangame** [comment]
maybe you can just clearRect  before drawImage,
for me it 's worked

**Comment by rttmax** [comment]
`      __draw: function __draw() {
                this.__clearCanvas();
                this.__ctx.drawImage(this.__frames[this.__frameIdx], 0, 0, this.__width, this.__height);
                this.__texture.needsUpdate = true;
            }`
This is working for me.

**Comment by mayognaise** [comment]
@keangameThank you and I'm sorry for the late response.
@rttmax Thank you so much for the response.
It's a shame I didn't clear each frame... 😱 
I will update this as soon as I get home.

**Comment by mayognaise** [comment]
hi @keangame @rttmax, do you mind to share the gif which actually works?
I tried using [the gif](http://belisario.herokuapp.com/belisariocorre_v01.gif) @tinchoforever shared and somehow it still didint work..

![image](https://d3vv6lp55qjaqc.cloudfront.net/items/2r21341z3T282z0Y182t/Screen%20Recording%202017-02-21%20at%2009.20%20AM.gif?X-CloudApp-Visitor-Id=1702050&v=68618b4d)

**Comment by rttmax** [comment]
i.e. http://i.stack.imgur.com/e8nZC.gif

**Comment by wiseshrimp** [comment]
When I did this fix, this fixed transparent gifs but messed up non-transparent gifs. Did anyone find a fix to make both work?

**Comment by sambshapiro** [comment]
@wiseshrimp is right. Adding `this.__clearCanvas();` to the draw function messes up non-transparent gifs.

**Comment by kencessna** [comment]
Hi, sorry but I don`t get this working at all! I tried your basic script and the screen stays write even though the paths are correct. And when I build a scene with basic geo and map a gif on one of them it the object stays white too. Please help!

Thanks for developing all this! Cheers, Can

**Comment by tinchoforever** [comment]
Hello everyone with @rttmax fix works ;)

` this.__clearCanvas(); this.__ctx.drawImage(this.__frames[this.__frameIdx], 0, 0, this.__width, this.__height); this.__texture.needsUpdate = true;`

**Comment by tinchoforever** [comment]
You can check 
https://belisario.herokuapp.com/ and 
https://belisario.herokuapp.com/ar/index.html

**Comment by tinchoforever** [comment]
And the base is here
https://github.com/tinchoforever/belisario.com.ar/blob/master/scripts/aframe-gif-shader.js

**Comment by sambshapiro** [comment]
@tinchoforever The fix only works if the gif is transparent; currently there is no solution that works for both transparent and non-transparent gifs.

**Comment by mayognaise** [comment]
Hi @rttmax I'm so sorry I didn't response when you give me the example.
I totally missed your comment as I was busy at the moment.
Thank you so much for fixing it. That's awesome.

@tinchoforever Thank you for sharing the link. However this link doesn't work for me.
https://github.com/tinchoforever/belisario.com.ar/blob/master/scripts/aframe-gif-shader.js
I guess maybe the repo is private?

 @sambshapiro I'll integrate it and will make it work both transparent and not. Also the code is super old so will optimize it.. no more `__` as standard..

@wiseshrimp Hmm I see.. I'm not sure if I can fix the issue..

**Comment by sambshapiro** [comment]
@mayognaise how will you determine whether or not the gif is transparent?

**Comment by mayognaise** [comment]
@sambshapiro i was gonna check if the material has `transparent: true;` 😆

**Comment by javismiles** [comment]
I have the same  issue, the gif is not clearing the previous frames, could you please update us on what's the recommended fix for that?

**Comment by javismiles** [comment]
for this fix, can you please explain where exactly  I have to add that code? thank you very much


`__draw: function __draw() { this.__clearCanvas(); this.__ctx.drawImage(this.__frames[this.__frameIdx], 0, 0, this.__width, this.__height); this.__texture.needsUpdate = true; }
This is working for me.`

**Comment by javismiles** [comment]
friends, I implemented the fix below and it works, great, BUT fit flickers, obviously the canvas deletion makes it flicker, how can we eliminate the flickering? thank u

`	this.__ctx.clearRect( 0, 0, this.__width, this.__height);
		this.__ctx.drawImage(this.__frames[this.__frameIdx], 0, 0, this.__width, this.__height); this.__texture.needsUpdate = true; `

**Comment by Angelo8828** [comment]
Sorry guys but any updates for this bug? Thanks

**Comment by tinchoforever** [comment]
Check here
https://github.com/tinchoforever/belisario.com.ar/blob/master/scripts/aframe-gif-shader.js

As Javier said, some times there are some flickers... but it works.



*Martín Nahuel Rabaglia*

Tech & Experiences Director / Co-Founder

[image: Imágenes integradas 4]

*genosha.com.ar <http://www.genosha.com.ar/>*

Phone: (+54)  9 11 2386 6243

Skype: martin.rabaglia

C.A.B.A - Argentina

**Comment by vettorazi** [comment]
@javismiles hey, i am wondering the same thing. can you please tell where did you put this snnipet?

**Comment by pablodiegoss** [comment]
It's been a long time since this issue was opened, but i've fixed this problem on #8, thought would be nice to cite it here o/

i've been using this GIF component on a [project](https://github.com/memeLab/ARte), check it out if you like :)

**Comment by mayoyml** [comment]
@pablodiegoss sorry i havent responsed this for long!
thank you so much for the contribution, will fix it this weekend!

**Comment by mayognaise** [comment]
Hi everyone here, I am so sorry it's been for so long since I commented last time... 🙏 
I finally updated the package: https://www.npmjs.com/package/aframe-gif-shader
@pablodiegoss I merged your PR, thank you so much 🙏

**Comment by Lizzy-gg** [comment]
Is the flickering of transparent animated gifs fixed yet? I still have this problem

**Comment by jrDev1** [comment]
I am having some really weird issues even with having the transparency set to false.
![B3463EE4-2A69-41A8-8025-E3BFC3BB8286](https://user-images.githubusercontent.com/16272193/85926910-8a0a4c00-b870-11ea-9c55-34d15f1b4299.jpeg)
![1AB31E95-D503-46C9-82EA-A8FE32FB45C3](https://user-images.githubusercontent.com/16272193/85926911-8aa2e280-b870-11ea-9449-16dec4532b7d.jpeg)

This is a black image with white background. It works fine on the MacBook but on iPhone it looks like that. Also looks like each gif frame is trimmed to the image then it fills in the background on its own (looking at the black edges of first pic...

**Comment by jrDev1** [comment]
Hello,

So I have figured out the issue with the black borders. It was because I was using the scale parameter. So I recommend to NOT use the scale parameter and use width and height parameters instead!

**Comment by dparker2** [comment]
![DD83D973-8624-40BF-8206-EC558180F32E](https://user-images.githubusercontent.com/22242367/147801759-633e25bb-51d3-4dda-8b57-6d8cf525f103.png)

Currently getting this behavior using the same banana gif in the example…
